dongExpander/config/routes.rb
Rails.application.routes.draw do
  resources :dongs
  resources :expands

  
  get '/', to: 'dongs#index'
  get '/dongs/expand', to: 'dongs#expand'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

dongExpander/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dongExpander/app/models/dong.rb
class Dong < ApplicationRecord
    has_one_attached :image
end

dongExpander/app/models/expand.rb
class Expand < ApplicationRecord
    has_many :dong
end

dongExpander/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

dongExpander/app/controllers/dongs_controller.rb
class DongsController < ApplicationController
  before_action :set_dong, only: [:show, :edit, :update, :destroy]

  # GET /dongs
  # GET /dongs.json
  def index
    @dongs = Dong.all
  end

  # GET /dongs/1
  # GET /dongs/1.json
  def show
  end

  # GET /dongs/new
  def new
    @dong = Dong.new
  end

  # GET /dongs/1/edit
  def edit
  end

  # POST /dongs
  # POST /dongs.json
  def create
    @dong = Dong.new(dong_params)

    respond_to do |format|
      if @dong.save
        format.html { redirect_to @dong, notice: 'Dong was successfully created.' }
        format.json { render :show, status: :created, location: @dong }
      else
        format.html { render :new }
        format.json { render json: @dong.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dongs/1
  # PATCH/PUT /dongs/1.json
  def update
    respond_to do |format|
      if @dong.update(dong_params)
        format.html { redirect_to @dong, notice: 'Dong was successfully updated.' }
        format.json { render :show, status: :ok, location: @dong }
      else
        format.html { render :edit }
        format.json { render json: @dong.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dongs/1
  # DELETE /dongs/1.json
  def destroy
    @dong.destroy
    respond_to do |format|
      format.html { redirect_to dongs_url, notice: 'Dong was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def expand
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dong
      @dong = Dong.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dong_params
      params.require(:dong).permit(:name, :image)
    end
end

dongExpander/app/controllers/expands_controller.rb
class ExpandsController < ApplicationController
  before_action :set_expand, only: [:show, :edit, :update, :destroy]

  # GET /expands
  # GET /expands.json
  def index
    @expand = Expand.new
    @expands = Expand.all
  end

  # GET /expands/1
  # GET /expands/1.json
  def show
    characters = @expand.text.chars
    #Set expanded dong
    dongs = Dong.all
    dongNames = dongs.map{|dong| dong.name}
    @images = []
    str = ""

    while characters.size > 0
        str += characters.shift
        if !dongNames.index(str).nil?
          @images.push(dongs[dongNames.index(str)].image)
          str = ""
        end
    end

    @text = str


  end

  # GET /expands/new
  def new
    @expand = Expand.new
  end

  # GET /expands/1/edit
  def edit
  end

  # POST /expands
  # POST /expands.json
  def create
    @expand = Expand.new(expand_params)

    respond_to do |format|
      if @expand.save
        format.html { redirect_to @expand, notice: 'Expand was successfully created.' }
        format.json { render :show, status: :created, location: @expand }
      else
        format.html { render :new }
        format.json { render json: @expand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expands/1
  # PATCH/PUT /expands/1.json
  def update
    respond_to do |format|
      if @expand.update(expand_params)
        format.html { redirect_to @expand, notice: 'Expand was successfully updated.' }
        format.json { render :show, status: :ok, location: @expand }
      else
        format.html { render :edit }
        format.json { render json: @expand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expands/1
  # DELETE /expands/1.json
  def destroy
    @expand.destroy
    respond_to do |format|
      format.html { redirect_to expands_url, notice: 'Expand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expand
      @expand = Expand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expand_params
      params.require(:expand).permit(:text)
    end
end

dongExpander/app/helpers/application_helper.rb
module ApplicationHelper
end

dongExpander/app/helpers/dongs_helper.rb
module DongsHelper
end

dongExpander/app/helpers/expands_helper.rb
module ExpandsHelper
end

dongExpander/app/views/dongs/_expand.html.erb
<%= form_tag("/dongs/expand", method: "get") do %>

  <%= label_tag(:text, "Text:") %>
  <%= text_field_tag(:text) %>
   
  <%= submit_tag 'Expand Dong'%>

<% end %>

dongExpander/app/views/dongs/_form.html.erb
<%= form_with(model: dong, local: true) do |form| %>
  <% if dong.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dong.errors.count, "error") %> prohibited this dong from being saved:</h2>

      <ul>
      <% dong.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

dongExpander/app/views/dongs/edit.html.erb
<h1>Editing Dong</h1>

<%= render 'form', dong: @dong %>

<%= link_to 'Show', @dong %> |
<%= link_to 'Back', dongs_path %>

dongExpander/app/views/dongs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dong Expander</h1>

<%= link_to 'Expand Dong', expands_path %>


<br/>
<br/>


<h1>Dong List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Preview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dongs.each do |dong| %>
      <tr>
        <td><%= dong.name %></td>
        <td><%= image_tag dong.image.variant(resize: "25x25") %></td>
        <td><%= link_to 'Show', dong %></td>
        <td><%= link_to 'Edit', edit_dong_path(dong) %></td>
        <td><%= link_to 'Destroy', dong, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dong', new_dong_path %>

dongExpander/app/views/dongs/new.html.erb
<h1>New Dong</h1>

<%= render 'form', dong: @dong %>

<%= link_to 'Back', dongs_path %>

dongExpander/app/views/dongs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dong.name %>
</p>

<%= image_tag @dong.image.variant(resize: "100x100") %>

<%= link_to 'Edit', edit_dong_path(@dong) %> |
<%= link_to 'Back', dongs_path %>

dongExpander/app/views/expands/_form.html.erb
<%= form_with(model: expand, local: true) do |form| %>
  <% if expand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expand.errors.count, "error") %> prohibited this expand from being saved:</h2>

      <ul>
      <% expand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

    <%= form.submit "Expand Dong" %>
<% end %>

dongExpander/app/views/expands/edit.html.erb
<h1>Editing Expand</h1>

<%= render 'form', expand: @expand %>

<%= link_to 'Show', @expand %> |
<%= link_to 'Back', expands_path %>

dongExpander/app/views/expands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expand Dong</h1>


<%= render 'form', expand: @expand %>

<br/>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expands.each do |expand| %>
      <tr>
        <td><%= expand.text %></td>
        <td><%= link_to 'Show', expand %></td>
        <td><%= link_to 'Edit', edit_expand_path(expand) %></td>
        <td><%= link_to 'Destroy', expand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Dongs', dongs_path %>

dongExpander/app/views/expands/new.html.erb
<h1>New Expand</h1>

<%= render 'form', expand: @expand %>

<%= link_to 'Back', expands_path %>

dongExpander/app/views/expands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @expand.text %>

  <br/>

  <% @images.each do |image| %>
    <%= image_tag image.variant(resize: "25x25") %>
  <% end %>

</p>

<%= link_to 'Edit', edit_expand_path(@expand) %> |
<%= link_to 'Back', expands_path %>

dongExpander/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DongExpander</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>